"""Add mobile_phone to User model

Revision ID: 246f6a88d9be
Revises: 
Create Date: 2024-10-16 00:41:15.245467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246f6a88d9be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editable_by', sa.String(length=20), nullable=True))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mobile_phone')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('editable_by')

    # ### end Alembic commands ###
